version: '3.4'

services:
  web:
    image: omni-peak/web
    restart: always
    build:
      context: ./web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000
    depends_on:
      - api
    
  api:
    image: omni-peak/api
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3333
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:  "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
    ports:
      - 5432
    volumes:
      - omni-peak-db-volume:/var/lib/postgresql
  
  nginx:
    image: omni-peak/nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT:-80}:80
    depends_on:
      - api
      - web

volumes:
  omni-peak-db-volume:
    external: true
    